const products = [
  {
    name: 'Monocristalino Half Cell 120 Células 460W Jinko',
    category: 'Módulo Fotovoltaico ',
    code: 'MFVJI-MO-120-460W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '1397.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/07/MFVJI-MO-120-460W-152x300.png',
  },
  {
    name: 'Policristalino Half Cell 156 Células 460W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFVHO-PO-156-460W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '1078.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/07/MFVHO-PO-156-460W-139x300.png',
  },
  {
    name: 'Monocristalino Half Cell 156 Células 600W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFVHO-MO-156-600W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '1699.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/07/MFVHO-MO-156-600W-131x300.png',
  },
  {
    name: 'Half Cell Monocristalino 132 Células 665W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFHON-MO-132-665W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '929.99',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/07/MFHON-MO-132-665W-196x300.png',
  },
  {
    name: 'Monocristalino Half Cell 144 Células 455W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFREN-MO-144-455W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '994.17',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/07/MFREN-MO-144-455W-197x300.jpg',
  },
  {
    name: 'Half Cell Monocristalino 144 Células 545W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFVCA-MO-144-545W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '2129.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/01/535-163x300.png',
  },
  {
    name: 'Half Cell Monocristalino 144 Células 540W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFVCA-MO-144-540W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '1690.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/01/535-163x300.png',
  },
  {
    name: 'Half Cell Monocristalino 144 Células 455W',
    category: 'Módulo Fotovoltaico ',
    code: 'MFVCA-MO-144-455W',
    description: 'Seguindo as principais tendências do mercado, nos quesitos qualidade, desempenho e custo benefício. Este módulo conta com células Half Cell monocristalinas de alta qualidade que garantem um fluxo de corrente mais uniforme, os vidros antirreflexo aprimoram a absorção de luz e reduzem a queda de desempenho devido as suas propriedades autolimpantes. A sua performance em situações de baixa irradiação, lhe proporcionam a capacidade de gerar energia desde o início da manhã, além de contar com resistência contra o PID (Degradação Induzida Potencial), proporcionando maior vida útil aos módulos.',
    price: '929.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/01/535-163x300.png',
  },
  {
    name: 'Dyness Powerbox 7.2kWh 48V 100Ah',
    category: 'Bateria',
    code: 'BATDY-48V-9.6KWH',
    description: 'A bateria armazenará o excesso de energia produzida a partir da energia solar durante o dia, podendo ser usado à noite para aumentar a autossuficiência e segurança energética ou usado no horário de pico para reduzir o consumo doméstico. A missão da Dyness é facilitar uma cadeia de energia mais saudável a um bom custo-benefício, onde consumidores e empresas de serviços públicos podem sair dos combustíveis convencionais que prejudicam nosso planeta para utilizar a energia limpa.',
    price: '17655.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/03/Dyness-Powerbox-7-243x300.png',
  },
  {
    name: 'Dyness Powerbox 4.8kWh 48V 100Ah',
    category: 'Bateria',
    code: 'BATDY-48V-7.2KWH',
    description: 'A bateria armazenará o excesso de energia produzida a partir da energia solar durante o dia, podendo ser usado à noite para aumentar a autossuficiência e segurança energética ou usado no horário de pico para reduzir o consumo doméstico. A missão da Dyness é facilitar uma cadeia de energia mais saudável a um bom custo-benefício, onde consumidores e empresas de serviços públicos podem sair dos combustíveis convencionais que prejudicam nosso planeta para utilizar a energia limpa.',
    price: '23.067.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/03/Dyness-Powerbox-7-243x300.png',
  },
  {
    name: 'Dyness Powerbox 9.6kWh 48V 200Ah',
    category: 'Bateria',
    code: 'BATDY-48V-4.8KWH',
    description: 'A bateria armazenará o excesso de energia produzida a partir da energia solar durante o dia, podendo ser usado à noite para aumentar a autossuficiência e segurança energética ou usado no horário de pico para reduzir o consumo doméstico. A missão da Dyness é facilitar uma cadeia de energia mais saudável a um bom custo-benefício, onde consumidores e empresas de serviços públicos podem sair dos combustíveis convencionais que prejudicam nosso planeta para utilizar a energia limpa.',
    price: '16980.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2022/03/Dyness-Powerbox-7-243x300.png',
  },
  {
    name: 'Cabo Solar 6mm 0.6/1KV AC 1.8KV VD Verde BelEnergy',
    category: 'Cabos',
    code: 'CBSOLBE-6MM-VD',
    description: 'Cabos Fotovoltaicos isolados com composto termofixo livre de halogênio e cobertos com composto termofixo e resistente a U.V., nas cores Vermelho, Preto.',
    price: '528.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2021/08/caboCD2-300x233.jpg.webp',
  },
  {
    name: 'Cabo Solar 6mm 0.6/1KV AC 1.8KV DC Vermelho BelEnergy',
    category: 'Cabos',
    code: 'CBSOLBE-6MM-VM',
    description: 'Cabo Solar Fotovoltaico isolado com composto termofixo livre de halogênio e cobertos com composto termofixo e resistente a U.V., Formado por fios de cobre eletrolítico estanhados, tempera mole, conforme NBR NM 280, classe 5 de encordoamento.',
    price: '799.00',
    image: 'https://belenergy.com.br/wp-content/uploads/2021/02/cbsolbe-6mm-vm_1-300x300.jpg.webp',
  },
  {
    name: 'Cabo Solar 6mm 0.6/1KV AC 1.8KV DC Preto BelEnergy',
    category: 'Cabos',
    code: 'CBSOLBE-6MM-PT',
    description: 'Cabos Fotovoltaicos isolados com composto termofixo livre de halogênio e cobertos com composto termofixo e resistente a U.V., nas cores Vermelho, Preto.',
    price: '309.90',
    image: 'https://belenergy.com.br/wp-content/uploads/2021/02/cbsolbe-6mm-pt_1-300x300.jpg.webp',
  },
  {
    name: 'Conector MC4 Macho e Fêmea',
    category: 'Conectores',
    code: 'CONECST-MC4',
    description: 'O conector MC4 é utilizado para realizar as conexões entre as partes do sistema fotovoltaico, garantindo segurança nas conexões e emendas de cabos, este conector reduz a perda de energia, tempos de inatividade, horas de serviço e risco de incêndio do seu sistema fotovoltaico, garantias essas asseguradas pela Stäubli. A tecnologia de contato MULTILAM única garantirá uma excelente confiabilidade a longo prazo e uma baixa resistência de contato durante toda a vida útil do produto.',
    price: '13.49',
    image: 'https://belenergy.com.br/wp-content/uploads/2021/02/Conecst-mca-01-300x300.jpg.webp',
  },
  {
    name: 'Conector Fêmea P/ Microinversores Deye',
    category: 'Conectores',
    code: 'CONECDE-FEAC',
    description: 'O conector femêa para microinversores Deye tem como sua função permitir a conexão do cabeamento que é direcionado ao quadro de energia do local instalado. Permitindo a transmissão da energia gerada pelo sistema fotovoltaico . Fabricado em alta qualidade garantindo longevidade para a instalação.',
    price: '11.87',
    image: 'https://belenergy.com.br/wp-content/uploads/2021/02/Conecde-feac-01-300x300.jpg.webp',
  },
  {
    name: 'Conector End Cap P/ Microinversores Deye',
    category: 'Conectores',
    code: 'CONECDE-ECAC',
    description: 'O conector End Cap para microinversores Deye tem como sua função bloquear a conexão do último conector livre da String. Fabricado em alta qualidade garantindo longevidade para a instalação.',
    price: '14.90',
    image: 'https://belenergy.com.br/wp-content/uploads/2021/02/Conecde-ecac-01-300x300.jpg.webp',
  }
]

export { products }